/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.view;

import interfaces.Interfaces;

/**
 *
 * @author edvan
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPlanoDeFundo = new javax.swing.JPanel();
        menuTituloLabel = new javax.swing.JLabel();
        navegarCadastroProdutoBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPlanoDeFundo.setBackground(new java.awt.Color(255, 255, 255));

        menuTituloLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTituloLabel.setText("Menu");

        navegarCadastroProdutoBotao.setText("Cadastrar produto");
        navegarCadastroProdutoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navegarCadastroProdutoBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPlanoDeFundoLayout = new javax.swing.GroupLayout(menuPlanoDeFundo);
        menuPlanoDeFundo.setLayout(menuPlanoDeFundoLayout);
        menuPlanoDeFundoLayout.setHorizontalGroup(
            menuPlanoDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlanoDeFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPlanoDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navegarCadastroProdutoBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(menuTituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPlanoDeFundoLayout.setVerticalGroup(
            menuPlanoDeFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlanoDeFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTituloLabel)
                .addGap(18, 18, 18)
                .addComponent(navegarCadastroProdutoBotao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPlanoDeFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPlanoDeFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navegarCadastroProdutoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navegarCadastroProdutoBotaoActionPerformed
        Interfaces.navegarCadastro();
        Interfaces.ocultarMenu();
    }//GEN-LAST:event_navegarCadastroProdutoBotaoActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel menuPlanoDeFundo;
    private javax.swing.JLabel menuTituloLabel;
    private javax.swing.JButton navegarCadastroProdutoBotao;
    // End of variables declaration//GEN-END:variables
}
